Profile: ConsultationNote
Parent: USRealmHeader
Id: Consultation-Note
Title: "Consultation Note"
Description: """The Consultation Note is generated by a request from a clinician for an opinion or advice from another clinician. Consultations may involve face-to-face time with the patient or may fall under the auspices of telemedicine visits. Consultations may occur while the patient is inpatient or ambulatory. The Consultation Note should also be used to summarize an Emergency Room or Urgent Care encounter.

A Consultation Note includes the reason for the referral, history of present illness, physical examination, and decision-making components (Assessment and Plan)."""
* ^meta.versionId = "18"
* ^meta.lastUpdated = "2020-08-19T06:51:00.403+00:00"
* ^meta.source = "#j21iyLdl5SyihDjY"
* ^publisher = "Lantana Consulting Group"
* ^contact[0].name = "Sarah Gaunt"
* ^contact[=].telecom[0].system = #phone
* ^contact[=].telecom[=].value = "+6-141-029-2506"
* ^contact[=].telecom[=].use = #work
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "sarah.gaunt@lantanagroup.com"
* ^contact[=].telecom[=].use = #work
* ^contact[+].name = "Rick Geimer"
* ^contact[=].telecom.system = #email
* ^contact[=].telecom.value = "rick.geimer@lantanagroup.com"
* ^contact[=].telecom.use = #work
* ^jurisdiction = urn:iso:std:iso:3166#US
* ^abstract = false
* type MS
* type from $2.16.840.1.113883.11.20.9.31 (required)
  * ^label = "Consultation Note"
  * ^short = "Consultation Note"
* encounter 1.. MS
  * ^label = "encompassingEncounter"
  * ^short = "encompassingEncounter"
* section ^slicing.discriminator.type = #value
  * ^slicing.discriminator.path = "code"
  * ^slicing.rules = #open
* section contains
    allergies_and_intolerances_section 1..1 MS and
    history_of_present_illness_section 1..1 MS and
    problem_section 1..1 and
    medications_section 0..1 and
    physical_exam_section 0..1 and
    results_section 0..1 and
    advance_directives_section 0..1 MS and
    assessment_and_plan_section 0..1 and
    assessment_section 0..1 and
    chief_complaint_and_reason_for_visit_section 0..1 and
    chief_complaint_section 0..1 and
    family_history_section 0..1 and
    functional_status_section 0..1 and
    general_status_section 0..1 and
    past_medical_history_section 0..1 and
    immunizations_section 0..1 and
    medical_equipment_section 0..1 and
    mental_status_section 0..1 and
    nutrition_section 0..1 and
    plan_of_treatment_section 0..1 and
    procedures_section 0..1 and
    reason_for_visit_section 0..1 and
    review_of_systems_section 0..1 and
    social_history_section 0..1 and
    vital_signs_section 0..1
* section[allergies_and_intolerances_section] ^label = "Allergies and Intolerances Section"
  * ^short = "Allergies and Intolerances Section"
  * ^comment = "Allergies and Intolerances Section"
  * title 1.. MS
    * ^short = "title"
  * code 1.. MS
  * code = $loinc#48765-2
    * ^label = "Allergies and adverse reactions"
    * ^short = "Allergies and adverse reactions"
  * text 1.. MS
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains allergy_intolerance_entry 0..*
  * entry[allergy_intolerance_entry] only Reference($us-core-allergyintolerance)
    * ^sliceName = "allergy_intolerance_entry"
    * ^mustSupport = true
* section[history_of_present_illness_section] ^label = "History of Present Illness Section"
  * ^short = "History of Present Illness Section"
  * ^comment = "History of Present Illness Section"
  * title 1.. MS
    * ^short = "title"
  * code 1.. MS
  * code = $loinc#10164-2
    * ^label = "History of present illness"
    * ^short = "History of present illness"
  * text 1.. MS
    * ^short = "This section contains only human readable content"
* section[problem_section] ^label = "Problem Section"
  * ^short = "Problem Section"
  * ^comment = "Problem Section"
  * title 1.. MS
    * ^short = "title"
  * code 1.. MS
  * code = $loinc#11450-4
    * ^label = "Problem list"
    * ^short = "Problem list"
  * text 1..
  * text only Narrative
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains problem_section_entry 0..*
  * entry[problem_section_entry] only Reference($us-core-condition)
    * ^sliceName = "problem_section_entry"
    * ^mustSupport = true
* section[medications_section] ^label = "Medications Section"
  * ^short = "Medications Section"
  * ^comment = "Medications Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#10160-0
    * ^label = "History of medication use"
    * ^short = "History of medication use"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference(MedicationStatement or $us-core-medication or $us-core-medicationrequest)
    * ^sliceName = "sliceEntry"
* section[physical_exam_section] ^label = "Physical Exam Section"
  * ^short = "Physical Exam Section"
  * ^comment = "Physical Exam Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#29545-1
    * ^label = "Physical findings"
    * ^short = "Physical findings"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference(Observation)
    * ^sliceName = "sliceEntry"
    * ^short = "This section contains unprofiled resources not covered by US Core. Please refer to C-CDA R2.1 for guidance on terminology, etc."
* section[results_section] ^label = "Results Section"
  * ^short = "Results Section"
  * ^comment = "Results Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#30954-2
    * ^label = "Relevant diagnostic tests/laboratory data"
    * ^short = "Relevant diagnostic tests/laboratory data"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference($us-core-observation-lab)
    * ^sliceName = "sliceEntry"
* section[advance_directives_section] ^label = "Advance Directives Section"
  * ^short = "Advance Directives Section"
  * ^comment = "Advance Directives Section"
  * title 1.. MS
    * ^short = "title"
  * code 1.. MS
  * code = $loinc#42348-3
    * ^label = "Advance directives"
    * ^short = "Advance directives"
  * text 1.. MS
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
  * entry contains advance_directive_entry 0..*
  * entry[advance_directive_entry] only Reference(Consent)
    * ^sliceName = "advance_directive_entry"
    * ^mustSupport = true
* section[assessment_and_plan_section] ^label = "Assessment and Plan Section"
  * ^short = "Assessment and Plan Section. This section represents the clinicianâs conclusions and working assumptions that will guide treatment of the patient. The Assessment and Plan Section may be combined or separated to meet local policy requirements."
  * ^comment = "Assessment and Plan Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#51847-2
    * ^label = "Assessment (evaluation) and plan"
    * ^short = "Assessment (evaluation) and plan"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference($us-core-condition or Observation or Communication)
    * ^sliceName = "sliceEntry"
    * ^short = "This section contains unprofiled resources not covered by US Core. Please refer to C-CDA R2.1 for guidance on terminology, etc."
* section[assessment_section] ^label = "Assessment Section"
  * ^short = "Assessment Section"
  * ^comment = "Assessment Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#51848-0
    * ^label = "Assessments (evaluation)"
    * ^short = "Assessments (evaluation)"
  * text 1..
    * ^short = "This section contains only human readable content"
* section[chief_complaint_and_reason_for_visit_section] ^label = "Chief Complaint and Reason for Visit Section"
  * ^short = "Chief Complaint and Reason for Visit Section. This section records the patient's chief complaint (the patientâs own description) and/or the reason for the patient's visit (the providerâs description of the reason for visit). Local policy determines whether the information is divided into two sections or recorded in one section serving both purposes."
  * ^comment = "Chief Complaint and Reason for Visit Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#46239-0
    * ^label = "Chief complaint and reason for visit"
    * ^short = "Chief complaint and reason for visit"
  * text 1..
    * ^short = "This section contains only human readable content"
* section[chief_complaint_section] ^label = "Chief Complaint Section"
  * ^short = "Chief Complaint Section"
  * ^comment = "Chief Complaint Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#10154-3
    * ^label = "Chief complaint"
    * ^short = "Chief complaint"
  * text 1..
    * ^short = "This section contains only human readable content"
* section[family_history_section] ^label = "Family History Section"
  * ^short = "Family History Section"
  * ^comment = "Family History Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#10157-6
    * ^label = "Family history"
    * ^short = "Family history"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference(FamilyMemberHistory)
    * ^sliceName = "sliceEntry"
    * ^short = "This section contains unprofiled resources not covered by US Core. Please refer to C-CDA R2.1 for guidance on terminology, etc."
* section[functional_status_section] ^label = "Functional Status Section"
  * ^short = "Functional Status Section"
  * ^comment = "Functional Status Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#47420-5
    * ^label = "Functional status"
    * ^short = "Functional status"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference(Observation)
    * ^sliceName = "sliceEntry"
    * ^short = "This section contains unprofiled resources not covered by US Core. Please refer to C-CDA R2.1 for guidance on terminology, etc."
* section[general_status_section] ^label = "General Status Section"
  * ^short = "General Status Section"
  * ^comment = "General Status Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#10210-3
    * ^label = "Physical findings of General status"
    * ^short = "Physical findings of General status"
  * text 1..
    * ^short = "This section contains only human readable content"
* section[past_medical_history_section] ^label = "Past Medical History Section"
  * ^short = "Past Medical History Section"
  * ^comment = "Past Medical History Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#11348-0
    * ^label = "Past Medical History"
    * ^short = "Past Medical History"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference($us-core-condition)
    * ^sliceName = "sliceEntry"
* section[immunizations_section] ^label = "Immunizations Section"
  * ^short = "Immunizations Section"
  * ^comment = "Immunizations Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#11369-6
    * ^label = "History of immunization"
    * ^short = "History of immunization"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference($us-core-immunization)
    * ^sliceName = "sliceEntry"
* section[medical_equipment_section] ^label = "Medical Equipment Section"
  * ^short = "Medical Equipment Section"
  * ^comment = "Medical Equipment Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#46264-8
    * ^label = "History of medical device use"
    * ^short = "History of medical device use"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains medical_equipment_entry 0..*
  * entry[medical_equipment_entry] only Reference(Device or $us-core-procedure)
    * ^sliceName = "medical_equipment_entry"
    * ^short = "This section contains unprofiled resources not covered by US Core. Please refer to C-CDA R2.1 for guidance on terminology, etc."
    * ^mustSupport = true
* section[mental_status_section] ^label = "Mental Status Section"
  * ^short = "Mental Status Section"
  * ^comment = "Mental Status Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#10190-7
    * ^label = "Mental status"
    * ^short = "Mental status"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference(Observation)
    * ^sliceName = "sliceEntry"
    * ^short = "This section contains unprofiled resources not covered by US Core. Please refer to C-CDA R2.1 for guidance on terminology, etc."
* section[nutrition_section] ^label = "Nutrition Section"
  * ^short = "Nutrition Section"
  * ^comment = "Nutrition Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#61144-2
    * ^label = "Diet and nutrition"
    * ^short = "Diet and nutrition"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference(NutritionOrder or ClinicalImpression)
    * ^sliceName = "sliceEntry"
    * ^short = "This section contains unprofiled resources not covered by US Core. Please refer to C-CDA R2.1 for guidance on terminology, etc."
* section[plan_of_treatment_section] ^label = "Plan of Treatment Section"
  * ^short = "Plan of Treatment Section"
  * ^comment = "Plan of Treatment Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#18776-5
    * ^label = "Plan of treatment"
    * ^short = "Plan of treatment"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains plan_of_treatment_entry 0..*
  * entry[plan_of_treatment_entry] only Reference($us-core-goal or $us-core-medicationrequest or $us-core-encounter or Communication or Appointment or CommunicationRequest or DeviceRequest or NutritionOrder or Task or ServiceRequest or VisionPrescription or RequestGroup)
    * ^short = "This section contains unprofiled resources not covered by US Core. Please refer to C-CDA R2.1 for guidance on terminology, etc."
* section[procedures_section] ^label = "Procedures Section"
  * ^short = "Procedures Section"
  * ^comment = "Procedures Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#47519-4
    * ^label = "History of Procedures"
    * ^short = "History of Procedures"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference($us-core-procedure)
    * ^sliceName = "sliceEntry"
* section[reason_for_visit_section] ^label = "Reason for Visit Section"
  * ^short = "Reason for Visit Section"
  * ^comment = "Reason for Visit Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#29299-5
    * ^label = "Reason for visit"
    * ^short = "Reason for visit"
  * text 1..
    * ^short = "This section contains only human readable content"
* section[review_of_systems_section] ^label = "Review of Systems Section"
  * ^short = "Review of Systems Section"
  * ^comment = "Review of Systems Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#10187-3
    * ^label = "Review of systems"
    * ^short = "Review of systems"
  * text 1..
    * ^short = "This section contains only human readable content"
* section[social_history_section] ^label = "Social History Section"
  * ^short = "Social History Section"
  * ^comment = "Social History Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#29762-2
    * ^label = "Social history"
    * ^short = "Social history"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains smokingStatusSliceEntry 0..*
  * entry[smokingStatusSliceEntry] only Reference($us-core-smokingstatus)
    * ^short = "Smoking status"
* section[vital_signs_section] ^label = "Vital Signs Section"
  * ^short = "Vital Signs Section"
  * ^comment = "Vital Signs Section"
  * title 1..
    * ^short = "title"
  * code 1..
  * code = $loinc#8716-3
    * ^label = "Vital signs"
    * ^short = "Vital signs"
  * text 1..
    * ^short = "text"
  * entry ^slicing.discriminator.type = #profile
    * ^slicing.discriminator.path = "resolve()"
    * ^slicing.rules = #open
    * ^short = "entry"
  * entry contains sliceEntry 0..*
  * entry[sliceEntry] only Reference($vitalsigns)
    * ^sliceName = "sliceEntry"
